### ISSUE TITLE
placeholder banners in "dev mode"

### ISSUE THREAD

**Issue by Ivshti** [AdExNetwork/adex-adview-manager#58]
Like this one:

![devs - 300x250px](https://user-images.githubusercontent.com/1247629/77000859-b05f4800-6961-11ea-9982-2086d4b4cff6.jpg)

**For all the regular sizes: https://github.com/AdExNetwork/adex-protocol/blob/master/campaignSpec.md#spec-properties-added-to-ipfs-and-can-not-be-modified**

**Comment by alesinka** [comment]
Here is a zip with all banner sizes: 
[adx-dev-banners.zip](https://github.com/AdExNetwork/adex-adview-manager/files/4354234/adx-dev-banners.zip)

**Comment by Ivshti** [comment]
Implemented
